<a href="https://colab.research.google.com/github/BOSOEK/Machine_Learning_with_Book/blob/main/Deep_Learning_Chatbot_for_First_Time/Embedding/one-hot-encodding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 원-핫 인코딩
> 단어를 벡터로 변환하는 기본적인 방법.(요소중 하나만 1, 나머지는 0)   

원-핫 인코딩의 결과를 원-핫 벡터 또는 희소 벡터라고도 한다.


In [6]:
from konlpy.tag import Komoran
import numpy as np

komoran = Komoran()
text = '오늘 날씨는 구름이 많아요.'

# 명사 추출
nouns = komoran.nouns(text)    # Konoran 형태소 분석기로 단어만 추출
print(nouns)

# 단어 사전 구축 및 단어별 인덱스 부여
dics = {}
for word in nouns:     # 뽑은 각 단어들을 딕셔너리로 저장
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

# 원-핫 인코딩
nb_classes = len(dics)    # 단어 사전 크기의 원-핫 벡터 크기 결정
targets = list(dics.values())      # 단어 사전을 리스트로 변환
one_hot_targets = np.eye(nb_classes)[targets]      # 넘파이의 eye() 함수로 원-핫 벡터 생성
print(one_hot_targets)

['오늘', '날씨', '구름']
{'오늘': 0, '날씨': 1, '구름': 2}
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


원-핫 인코딩의 경우는 구현 대비 좋은 성능으로 자주 사용되지만, __단어의 의미나 유사 단어와의 관계는 담지 않고, 단어 사전 크기에 따라 원-핫 벡터도 커져__ 메모리 낭비가 일어나는 문제가 생길수 도 있다.